vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        users:
            uri_prefix: /uploads/images/users
            upload_destination: '%kernel.project_dir%/public/uploads/images/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        cooptations:
            uri_prefix: /uploads/cv
            upload_destination: '%kernel.project_dir%/public/uploads/cv'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true





