vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        users:
            uri_prefix: /uploads/images/users
            upload_destination: '%kernel.project_dir%/public/uploads/images/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        cooptations:
            uri_prefix: /uploads/cv
            upload_destination: '%kernel.project_dir%/public/uploads/cooptation/cv'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        formation:
            uri_prefix: /uploads/images/formation
            upload_destination: '%kernel.project_dir%/public/uploads/images/formation'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        event:
            uri_prefix: /uploads/images/event
            upload_destination: '%kernel.project_dir%/public/uploads/images/event'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true





